// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVfjnFeBNHRELcikKVX45q9g20zBn9Kuc',
    appId: '1:1088764063334:web:e584f37f1202812e3bc7a7',
    messagingSenderId: '1088764063334',
    projectId: 'akilli-tebesir',
    authDomain: 'akilli-tebesir.firebaseapp.com',
    storageBucket: 'akilli-tebesir.firebasestorage.app',
    measurementId: 'G-VWZVQBHYWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9YE7LTh8APTZjj_Kzu6wuESOEMIL49Ds',
    appId: '1:1088764063334:android:433e7af9d754c97f3bc7a7',
    messagingSenderId: '1088764063334',
    projectId: 'akilli-tebesir',
    storageBucket: 'akilli-tebesir.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw5lUS3yAfep1dpb9KGbemFheELXwF_ak',
    appId: '1:1088764063334:ios:b49fc42b845614d63bc7a7',
    messagingSenderId: '1088764063334',
    projectId: 'akilli-tebesir',
    storageBucket: 'akilli-tebesir.firebasestorage.app',
    iosBundleId: 'com.example.odevTakip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw5lUS3yAfep1dpb9KGbemFheELXwF_ak',
    appId: '1:1088764063334:ios:b49fc42b845614d63bc7a7',
    messagingSenderId: '1088764063334',
    projectId: 'akilli-tebesir',
    storageBucket: 'akilli-tebesir.firebasestorage.app',
    iosBundleId: 'com.example.odevTakip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVfjnFeBNHRELcikKVX45q9g20zBn9Kuc',
    appId: '1:1088764063334:web:37fa5a17b580eae03bc7a7',
    messagingSenderId: '1088764063334',
    projectId: 'akilli-tebesir',
    authDomain: 'akilli-tebesir.firebaseapp.com',
    storageBucket: 'akilli-tebesir.firebasestorage.app',
    measurementId: 'G-9NDMYX6PBT',
  );
}
